# This file was generated by GoReleaser. DO NOT EDIT.
cask "hmon" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "3b902ecceb5ceb12d5fd85338ed6ab36c6f9d723990b459a0592246463621aa5"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "141926e8ff620666115e482e6f04a88578b854aa50891e2655b08963748617a5"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "73f900363ccaf4ba3ae4d9236917221359b875ee9cf8b1491943fa26c9d8dd61"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4dbb7a779601eea6f425ec1e9b973e3bf067a279139c612ff604f0a5ffdd847"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hmon"
  desc "Terminal dashboard for a small fleet of Linux machines over SSH"
  homepage "https://github.com/Sousf/hmon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hmon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/hmon"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    hmon reads ~/.config/hmon/config.yaml. Create a starter one with:

      mkdir -p ~/.config/hmon
      hmon -example > ~/.config/hmon/config.yaml

    Connection details come from ~/.ssh/config, so each host is usually
    just its alias.
  EOS
end
