# This file was generated by GoReleaser. DO NOT EDIT.
cask "hmon" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c593f34f4f90417e545151412a0cdb7c30bf2ac333db18a06a8ce2c8b59781a4"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f35abaaf80d293fdf5c6e55cf17a8d7db148fe1294e6a5c8fb1144238ba893d5"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8a0f4f83793e93348efb61f717b994489731ef79b1318e1511ee4da4496646fb"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "39b866bbb03824c84f91943fbc05ed6f708e3913bc4ca4731cbfdd31c19e350a"
      url "https://github.com/Sousf/hmon/releases/download/v#{version}/hmon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hmon"
  desc "Terminal dashboard for a small fleet of Linux machines over SSH"
  homepage "https://github.com/Sousf/hmon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hmon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/hmon"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    hmon reads ~/.config/hmon/config.yaml. Create a starter one with:

      mkdir -p ~/.config/hmon
      hmon -example > ~/.config/hmon/config.yaml

    Connection details come from ~/.ssh/config, so each host is usually
    just its alias.
  EOS
end
