# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hmon < Formula
  desc "Terminal dashboard for a small fleet of Linux machines over SSH"
  homepage "https://github.com/Sousf/hmon"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sousf/hmon/releases/download/v0.4.0/hmon_0.4.0_darwin_amd64.tar.gz"
      sha256 "1e02ec1e6fbce33b74dad6a53f99b691f2b4d905df2fc9c16d5bc6a8da9f62aa"

      define_method(:install) do
        bin.install "hmon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sousf/hmon/releases/download/v0.4.0/hmon_0.4.0_darwin_arm64.tar.gz"
      sha256 "07cc881356dd22ce0a6874c117dda0370569b87cf4fdc73d7bab22225d9fd3c6"

      define_method(:install) do
        bin.install "hmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sousf/hmon/releases/download/v0.4.0/hmon_0.4.0_linux_amd64.tar.gz"
      sha256 "d653ae5c4167f07d849c2ef4da9a264f0483523bd1e982e2b3cf5b4e109f5547"
      define_method(:install) do
        bin.install "hmon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sousf/hmon/releases/download/v0.4.0/hmon_0.4.0_linux_arm64.tar.gz"
      sha256 "b9341cef8100c683395d2f37934dab427383ae83d2852a48544b615278df98e0"
      define_method(:install) do
        bin.install "hmon"
      end
    end
  end

  def caveats
    <<~EOS
      hmon reads ~/.config/hmon/config.yaml. Create a starter one with:

        mkdir -p ~/.config/hmon
        hmon -example > ~/.config/hmon/config.yaml

      Connection details come from ~/.ssh/config, so each host is usually
      just its alias.
    EOS
  end

  test do
    # -example needs no config, no network, and no TTY, so it is the only
    # command that can meaningfully run under `brew test`.
    assert_match "hosts:", shell_output("#{bin}/hmon -example")
  end
end
