# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hmon < Formula
  desc "Terminal dashboard for a small fleet of Linux machines over SSH"
  homepage "https://github.com/Sousf/hmon"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sousf/hmon/releases/download/v0.5.0/hmon_0.5.0_darwin_amd64.tar.gz"
      sha256 "4878ba42326c706fae4dd33c335645fe17475cc3a93374f69c80f7793aa82d0b"

      define_method(:install) do
        bin.install "hmon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sousf/hmon/releases/download/v0.5.0/hmon_0.5.0_darwin_arm64.tar.gz"
      sha256 "773cac2b08bc5fa3a88a5a6fe469767aecad2e6192db8924d31f3ef1950d22aa"

      define_method(:install) do
        bin.install "hmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sousf/hmon/releases/download/v0.5.0/hmon_0.5.0_linux_amd64.tar.gz"
      sha256 "f8468e20b5644e2f40d18ac6bb63804625f4603c5732e430d28ec68a309f3aa3"
      define_method(:install) do
        bin.install "hmon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sousf/hmon/releases/download/v0.5.0/hmon_0.5.0_linux_arm64.tar.gz"
      sha256 "57738fdca7b1c4254641b6c8caf12fa9411db54b8a1ee259cf27fcb80c3b499e"
      define_method(:install) do
        bin.install "hmon"
      end
    end
  end

  def caveats
    <<~EOS
      hmon reads ~/.config/hmon/config.yaml. Create a starter one with:

        mkdir -p ~/.config/hmon
        hmon -example > ~/.config/hmon/config.yaml

      Connection details come from ~/.ssh/config, so each host is usually
      just its alias.
    EOS
  end

  test do
    # -example needs no config, no network, and no TTY, so it is the only
    # command that can meaningfully run under `brew test`.
    assert_match "hosts:", shell_output("#{bin}/hmon -example")
  end
end
