# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hmon < Formula
  desc "Terminal dashboard for a small fleet of Linux machines over SSH"
  homepage "https://github.com/Sousf/hmon"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sousf/hmon/releases/download/v0.8.0/hmon_0.8.0_darwin_amd64.tar.gz"
      sha256 "d807b9bbe46c91e492c2a6a4532375194be8f655d2f90b50c93fab12a94d01a7"

      define_method(:install) do
        bin.install "hmon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sousf/hmon/releases/download/v0.8.0/hmon_0.8.0_darwin_arm64.tar.gz"
      sha256 "7a96c2faae2082b36eda71954a9688b5cb5d40b51a05061bc01a1310739e599d"

      define_method(:install) do
        bin.install "hmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sousf/hmon/releases/download/v0.8.0/hmon_0.8.0_linux_amd64.tar.gz"
      sha256 "1a7b1a648d2b87a6aaee811858486210223f2cf67daf6363a606306f32ca142d"
      define_method(:install) do
        bin.install "hmon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sousf/hmon/releases/download/v0.8.0/hmon_0.8.0_linux_arm64.tar.gz"
      sha256 "547de55e9293d47a980e001f51cfdaeb8010375d0a9098839b4967aca97cb650"
      define_method(:install) do
        bin.install "hmon"
      end
    end
  end

  def caveats
    <<~EOS
      hmon reads ~/.config/hmon/config.yaml. Create a starter one with:

        mkdir -p ~/.config/hmon
        hmon -example > ~/.config/hmon/config.yaml

      Connection details come from ~/.ssh/config, so each host is usually
      just its alias.
    EOS
  end

  test do
    # -example needs no config, no network, and no TTY, so it is the only
    # command that can meaningfully run under `brew test`.
    assert_match "hosts:", shell_output("#{bin}/hmon -example")
  end
end
